// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb5nRWVmz5-YS0fafvnuXn2fR8hwemVrU',
    appId: '1:621028926504:web:4d9b5e9fa4a92c4afb011d',
    messagingSenderId: '621028926504',
    projectId: 'botecaria-1',
    authDomain: 'botecaria-1.firebaseapp.com',
    storageBucket: 'botecaria-1.firebasestorage.app',
    measurementId: 'G-NZXT4WXQ24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGxgRnQdLMTfmW_hmNtb9SwxODXVs55b8',
    appId: '1:621028926504:android:76227863f8ce4610fb011d',
    messagingSenderId: '621028926504',
    projectId: 'botecaria-1',
    storageBucket: 'botecaria-1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb5nRWVmz5-YS0fafvnuXn2fR8hwemVrU',
    appId: '1:621028926504:web:e99b477a79ec255bfb011d',
    messagingSenderId: '621028926504',
    projectId: 'botecaria-1',
    authDomain: 'botecaria-1.firebaseapp.com',
    storageBucket: 'botecaria-1.firebasestorage.app',
    measurementId: 'G-04GS1BCNPL',
  );
}
